name: 网易云飞升

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 16 * * *"
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Python3
        uses: actions/setup-python@master
        with:
          python-version: 3.7
      - name: Extension
        run: |
          pip3 install -r requirements.txt
      - name: Run Script
        env:
          PHONE: ${{ secrets.PHONE }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python3 action.py ${PHONE} ${PASSWORD}
